@php
    use App\Models\HotelDetail;

    $hotel = HotelDetail::first();
@endphp

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{{ $title ?? 'Report' }}</title>
    <style>
        body {
            font-family: "DejaVu Sans", sans-serif;
            color: #333;
            font-size: 12px;
            margin: 20px;
        }

        .header {
            display: flex;
            align-items: center;
            justify-content: space-between;
            border-bottom: 2px solid #444;
            padding-bottom: 10px;
            margin-bottom: 15px;
        }

        .header-left {
            display: flex;
            align-items: center;
        }

        .header-left img {
            height: 60px;
            width: auto;
            margin-right: 12px;
        }

        .hotel-info h1 {
            font-size: 18px;
            margin: 0;
            color: #222;
        }

        .hotel-info div {
            font-size: 12px;
            color: #555;
        }

        h2 {
            text-align: center;
            color: #222;
            text-transform: uppercase;
            margin-bottom: 10px;
        }

        .filters {
            margin-bottom: 15px;
            text-align: center;
            font-size: 12px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
            page-break-inside: auto;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 6px 8px;
            text-align: left;
            font-size: 11px;
        }

        th {
            background-color: #f3f3f3;
            font-weight: bold;
            text-transform: capitalize;
        }

        tr:nth-child(even) {
            background-color: #fafafa;
            page-break-inside: avoid page-break-after: auto;
        }
        ,
        thead {
            display: table-header-group;
        }

        tbody {
            display: table-row-group;
        }

        .footer {
            margin-top: 30px;
            font-size: 11px;
            color: #666;
            text-align: center;
        }

        .footer div {
            margin-top: 4px;
        }
    </style>
</head>

<body>

    @php
        $hotel = HotelDetail::first();
    @endphp

    {{-- Hotel Header --}}
    @if($hotel)
        <div class="header">
            <div class="header-left">
                @if($hotel->logo)
                    @php
                        $logoPath = storage_path('app/public/' . $hotel->logo);
                        $logoData = file_exists($logoPath)
                            ? 'data:image/' . pathinfo($logoPath, PATHINFO_EXTENSION) . ';base64,' . base64_encode(file_get_contents($logoPath))
                            : null;
                    @endphp
                    @if($logoData)
                        <img src="{{ $logoData }}" alt="Hotel Logo">
                    @endif
                @endif
                <div class="hotel-info">
                    <h1>{{ $hotel->name }}</h1>
                    <div>{{ $hotel->address }}</div>
                    <div>Phone: {{ $hotel->phone_number }} | Email: {{ $hotel->email }}</div>
                    <div>Website: {{ $hotel->website }}</div>
                </div>
            </div>
        </div>
    @endif

    {{-- Report Title --}}
    <h2>{{ $title ?? 'System Report' }}</h2>

    {{-- Filter Section --}}
    @if(!empty($filters['from_date']) || !empty($filters['to_date']))
        <div class="filters">
            <strong>Report Period:</strong>
            {{ $filters['from_date'] ?? '—' }} → {{ $filters['to_date'] ?? '—' }}
        </div>
    @endif

    {{-- Data Table --}}
    <table>
        <thead>
            <tr>
                <th>#</th>
                @foreach($columns as $col)
                    <th>{{ ucwords(str_replace(['.', '_'], ' ', $col)) }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse($data as $index => $row)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    @foreach($columns as $col)
                        <td>{{ data_get($row, $col, '—') }}</td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($columns) + 1 }}" style="text-align:center;">No data found for the selected
                        filters.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    {{-- Footer --}}
    <div class="footer">
        <div><strong>Generated on:</strong> {{ now()->format('Y-m-d H:i') }}</div>
        <div><strong>Generated by:</strong> {{ auth()->user()->fname ?? 'System Administrator' }}</div>
        @if($hotel)
            <div><em>{{ $hotel->name }} — Confidential Report</em></div>
        @endif
    </div>

</body>

</html>